# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Set the environment variable
ENV FLASK_APP=app.py

# Expose the Flask port
EXPOSE 5000

# Run the command to start the Flask app
CMD [ "flask", "run", "--host=0.0.0.0" ]
