"""tabela agendamento

Revision ID: d038331dc55b
Revises: 4561a8a6ee7d
Create Date: 2023-02-24 21:51:36.939604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd038331dc55b'
down_revision = '4561a8a6ee7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('data_agendamento', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('servicos_desejados', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamento')
    # ### end Alembic commands ###
